server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;

        # Disable caching for index.html to ensure clients always get the latest bundle
        location = /index.html {
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            expires off;
        }
    }

    location /api/ {
        proxy_pass http://backend:8080/api/;
    }

    location /uploads/ {
        proxy_pass http://backend:8080/uploads/;
    }

    location /ws {
        proxy_pass http://backend:8080/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location /admin/login {
        proxy_pass http://backend:8080/admin/login;
    }

    location /admin/create {
        proxy_pass http://backend:8080/admin/create;
    }

    location /admin/list {
        proxy_pass http://backend:8080/admin/list;
    }

    location /admin/delete/ {
        proxy_pass http://backend:8080/admin/delete/;
    }
}
